/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        align: 'center',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    height: 150,
                    maxWidth: 700,
                    width: 700,
                    header: false,
                    title: 'Header'
                },
                {
                    xtype: 'panel',
                    maxWidth: 700,
                    minHeight: 800,
                    width: 700,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    header: false,
                    title: 'Body',
                    items: [
                        {
                            xtype: 'panel',
                            margins: '1',
                            maxWidth: 200,
                            width: 200,
                            title: 'Nav'
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    title: 'My Form',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            maxWidth: 300,
                                            fieldLabel: 'Identifiant'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            maxWidth: 300,
                                            fieldLabel: 'Mot de passe'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'MyButton'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});